# Generated by Django 4.0.4 on 2022-05-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreetLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=255)),
                ('BV', models.FloatField()),
                ('BI', models.FloatField()),
                ('SV', models.FloatField()),
                ('SI', models.FloatField()),
                ('LV', models.FloatField()),
                ('LI', models.FloatField()),
                ('BA', models.FloatField()),
                ('STATE', models.CharField(max_length=255)),
                ('LAT', models.FloatField()),
                ('LON', models.FloatField()),
                ('DRY_BIN', models.FloatField()),
                ('WET_BIN', models.FloatField()),
                ('TIME_STAMP', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
