# Generated by Django 4.0.4 on 2022-05-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetlightrequesthandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetlight',
            name='DRY_BIN',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='streetlight',
            name='LAT',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='streetlight',
            name='LON',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='streetlight',
            name='WET_BIN',
            field=models.CharField(max_length=255),
        ),
    ]
