# Generated by Django 4.0.4 on 2022-05-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetlightrequesthandler', '0002_alter_streetlight_dry_bin_alter_streetlight_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetlight',
            name='TIME_STAMP',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
