# Generated by Django 4.0.4 on 2022-05-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetlightrequesthandler', '0003_alter_streetlight_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetlight',
            name='TIME_STAMP',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
