# Generated by Django 4.0.4 on 2022-05-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetlightrequesthandler', '0004_alter_streetlight_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='streetlight',
            name='DATE',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='streetlight',
            name='TIME_STAMP',
            field=models.TimeField(auto_now=True),
        ),
    ]
