# Generated by Django 4.0.4 on 2022-05-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetlightrequesthandler', '0005_streetlight_date_alter_streetlight_time_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreetLightHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=255)),
                ('BV', models.FloatField()),
                ('BI', models.FloatField()),
                ('SV', models.FloatField()),
                ('SI', models.FloatField()),
                ('LV', models.FloatField()),
                ('LI', models.FloatField()),
                ('BA', models.FloatField()),
                ('STATE', models.CharField(max_length=255)),
                ('LAT', models.CharField(max_length=255)),
                ('LON', models.CharField(max_length=255)),
                ('DRY_BIN', models.CharField(max_length=255)),
                ('WET_BIN', models.CharField(max_length=255)),
                ('DATE', models.DateField()),
                ('TIME_STAMP', models.TimeField()),
            ],
        ),
    ]
