# Generated by Django 4.0.4 on 2022-05-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetlightrequesthandler', '0006_streetlighthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetlighthistory',
            name='DATE',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='streetlighthistory',
            name='TIME_STAMP',
            field=models.TimeField(auto_now=True),
        ),
    ]
