# Generated by Django 4.0.4 on 2022-05-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetlightrequesthandler', '0007_alter_streetlighthistory_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetlighthistory',
            name='DATE',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='streetlighthistory',
            name='TIME_STAMP',
            field=models.TimeField(),
        ),
    ]
